---
- name: Run pkginfo module
  hosts: all
  become: true
  become_method: sudo

  # Gather Fatc
  pre_tasks:

  - name: "Gather fact"
    setup:
      filter:
      - 'ansible_os_family'

  tasks:

  # check OS Type
  - name: "Check OS Type"
    fail:
      msg: The system is not Solaris
    when: ( ansible_os_family != "Solaris" )

  # run custom
  - name: gather facts of SUNWzoneu pkg on Solaris 10
    pkginfo_facts:
      pkgname: "SUNWzoneu"
      alias: zone    
  
  - name: set fact for print
    set_fact:
      zone_status: "{{ ansible_facts.zone_pkg| map(attribute='STATUS') | first }}"
      zone_version: "{{ ansible_facts.zone_pkg| map(attribute='VERSION') | first }}"    
  
  - name: print SUNWzoneu pkg status and version
    debug:
      msg: "zone pkg is {{zone_status}}. Version : {{zone_version}} "    
