---
- name: Run pkginfo module
  hosts: all
  become: true
  become_method: sudo

  # Gather Fatc
  pre_tasks:

  - name: "Gather fact"
    setup:
      filter:
      - 'ansible_os_family'

  tasks:

  # check OS Type
  - name: "Check OS Type"
    fail:
      msg: The system is not Solaris
    when: ( ansible_os_family != "Solaris" )

  # run custom
  - name: gather facts of sendmail pkg on Solaris 11
    pkginfo_facts:
      pkgname: "service/network/smtp/sendmail"
      alias: sendmail
  
  - name: set fact for print
    set_fact:
      sendmail_state: "{{ ansible_facts.sendmail_pkg| map(attribute='State') | first }}"
      sendmail_version: "{{ ansible_facts.sendmail_pkg| map(attribute='Version') | first }}"
  
  - name: print sendmail pkg state and version
    debug:
      msg: "sendmail pkg is {{sendmail_state}}. Version : {{sendmail_version}} "   
